on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    name: Deploy
    uses: peter-evans/repository-dispatch@v1
    with:
      token: ${{ secrets.REPO_ACCESS_TOKEN }}
      repository: RomainMichau/rokim_conf
      event-type: trigger-deploy
