name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: rust_build_test
    runs-on: self-hosted
    container:
      image: rust
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  test_build_docker:
      name: dockerbuild-test
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Set image tag
        run: echo "::set-env name=IMAGE_TAG::connect4_rust_$(date +%s)"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
      - name: Remove the Docker image
        run: docker rmi ${{ env.IMAGE_TAG }}
