name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: rust_build_test
    runs-on: self-hosted
    container:
      image: rust
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  docker_build:
    name: docker_build
    runs-on: self-hosted
    container:
      image: docker:dind
      options: --privileged --group-add 116
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -t myimage .
